<a href="https://colab.research.google.com/github/7206582513/First-HTML/blob/main/Untitled24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Travel.csv")

In [43]:
df.head(10)

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
5,200005,0,32.0,Company Invited,1,8.0,Salaried,Male,3,3.0,Basic,3.0,Single,1.0,0,5,1,1.0,Executive,18068.0
6,200006,0,59.0,Self Enquiry,1,9.0,Small Business,Female,2,2.0,Basic,5.0,Divorced,5.0,1,2,1,1.0,Executive,17670.0
7,200007,0,30.0,Self Enquiry,1,30.0,Salaried,Male,3,3.0,Basic,3.0,Married,2.0,0,2,0,1.0,Executive,17693.0
8,200008,0,38.0,Company Invited,1,29.0,Salaried,Male,2,4.0,Standard,3.0,Unmarried,1.0,0,3,0,0.0,Senior Manager,24526.0
9,200009,0,36.0,Self Enquiry,1,33.0,Small Business,Male,3,3.0,Deluxe,3.0,Divorced,7.0,0,3,1,0.0,Manager,20237.0

In [44]:
df.describe()

,CustomerID,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
count,4888.000000,4888.000000,4662.000000,4888.000000,4637.000000,4888.000000,4843.000000,4862.000000,4748.000000,4888.000000,4888.000000,4888.000000,4822.000000,4655.000000
mean,202443.500000,0.188216,37.622265,1.654255,15.490835,2.905074,3.708445,3.581037,3.236521,0.290917,3.078151,0.620295,1.187267,23619.853491
std,1411.188388,0.390925,9.316387,0.916583,8.519643,0.724891,1.002509,0.798009,1.849019,0.454232,1.365792,0.485363,0.857861,5380.698361
min,200000.000000,0.000000,18.000000,1.000000,5.000000,1.000000,1.000000,3.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1000.000000
25%,201221.750000,0.000000,31.000000,1.000000,9.000000,2.000000,3.000000,3.000000,2.000000,0.000000,2.000000,0.000000,1.000000,20346.000000
50%,202443.500000,0.000000,36.000000,1.000000,13.000000,3.000000,4.000000,3.000000,3.000000,0.000000,3.000000,1.000000,1.000000,22347.000000
75%,203665.250000,0.000000,44.000000,3.000000,20.000000,3.000000,4.000000,4.000000,4.000000,1.000000,4.000000,1.000000,2.000000,25571.000000
max,204887.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,5.000000,1.000000,3.000000,98678.000000

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4888 entries, 0 to 4887
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                4888 non-null   int64
 1   ProdTaken                 4888 non-null   int64
 2   Age                       4662 non-null   float64
 3   TypeofContact             4863 non-null   object
 4   CityTier                  4888 non-null   int64
 5   DurationOfPitch           4637 non-null   float64
 6   Occupation                4888 non-null   object
 7   Gender                    4888 non-null   object
 8   NumberOfPersonVisiting    4888 non-null   int64
 9   NumberOfFollowups         4843 non-null   float64
 10  ProductPitched            4888 non-null   object
 11  PreferredPropertyStar     4862 non-null   float64
 12  MaritalStatus             4888 non-null   object
 13  NumberOfTrips             4748 non-null   float64
 14  Passport                  4888 non-null   int64
 15  PitchSatisfactionScore    4888 non-null   int64
 16  OwnCar                    4888 non-null   int64
 17  NumberOfChildrenVisiting  4822 non-null   float64
 18  Designation               4888 non-null   object
 19  MonthlyIncome             4655 non-null   float64
dtypes: float64(7), int64(7), object(6)
memory usage: 763.9+ KB

In [3]:
df

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [46]:
age_distribution = df['Age'].value_counts().sort_index(ascending=True)
age_distribution

18.0     14
19.0     32
20.0     38
21.0     41
22.0     46
23.0     46
24.0     56
25.0     74
26.0    106
27.0    138
28.0    147
29.0    178
30.0    199
31.0    203
32.0    197
33.0    189
34.0    211
35.0    237
36.0    231
37.0    185
38.0    176
39.0    150
40.0    146
41.0    155
42.0    142
43.0    130
44.0    105
45.0    116
46.0    121
47.0     88
48.0     65
49.0     65
50.0     86
51.0     90
52.0     68
53.0     66
54.0     61
55.0     64
56.0     58
57.0     29
58.0     31
59.0     44
60.0     29
61.0      9
Name: Age, dtype: int64

In [48]:
age_purchase_relation = df.groupby('Age')['ProductPitched'].value_counts().unstack(fill_value=0)
age_purchase_relation

ProductPitched  Basic  Deluxe  King  Standard  Super Deluxe
Age
18.0               14       0     0         0             0
19.0               31       0     0         1             0
20.0               37       0     0         1             0
21.0               40       1     0         0             0
22.0               43       3     0         0             0
23.0               41       5     0         0             0
24.0               46      10     0         0             0
25.0               43      31     0         0             0
26.0               61      44     0         1             0
27.0               83      45     1         9             0
28.0               91      43     1        12             0
29.0              109      52     0        16             1
30.0              105      67     0        26             1
31.0               83      87     0        32             1
32.0               72      97     0        27             1
33.0               75      88     0        22             4
34.0               83      96     0        27             5
35.0               88      98     0        50             1
36.0               78      92     0        61             0
37.0               58      81     0        46             0
38.0               54      81     0        41             0
39.0               33      70     5        33             9
40.0               25      61    14        29            17
41.0               35      59    19        26            16
42.0               36      54    18        16            18
43.0               32      51    11        15            21
44.0               35      33     8        15            14
45.0               34      40     9        22            11
46.0               13      44    12        33            19
47.0                4      32    11        23            18
48.0               10      24     5        13            13
49.0                8      20     9        15            13
50.0               10      19    22        13            22
51.0               17      19    18        15            21
52.0               13      17     9        14            15
53.0                7      14    10        12            23
54.0                0      17     6        17            21
55.0                3      17    12        14            18
56.0               13       9    13         7            16
57.0                9       5     3         5             7
58.0                7       6     3         8             7
59.0               13       7     5        12             7
60.0                6       8     4         9             2
61.0                0       4     2         3             0

In [6]:
contact_liked_product= df.groupby("TypeofContact")['ProductPitched'].value_counts()

In [7]:
contact_liked_product

TypeofContact    ProductPitched
Company Invited  Deluxe             541
                 Basic              516
                 Standard           218
                 Super Deluxe        96
                 King                48
Self Enquiry     Basic             1316
                 Deluxe            1176
                 Standard           524
                 Super Deluxe       246
                 King               182
Name: ProductPitched, dtype: int64

In [8]:
contact_liked_product= df.groupby("TypeofContact")['ProductPitched'].value_counts().unstack(fill_value=0)

In [9]:
contact_liked_product

ProductPitched   Basic  Deluxe  King  Standard  Super Deluxe
TypeofContact
Company Invited    516     541    48       218            96
Self Enquiry      1316    1176   182       524           246

In [ ]:
df

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [10]:
average_duration_purchased = df[df['ProductPitched'] == 'Deluxe']['DurationOfPitch'].mean()
average_duration_not_purchased = df[df['ProductPitched'] != 'Deluxe']['DurationOfPitch'].mean()
average_duration_purchased

15.935839274141284

In [11]:
average_duration_not_purchased

15.268907563025211

In [12]:
occupation_distribution = df['Occupation'].value_counts()

In [49]:
occupation_distribution

Salaried          2368
Small Business    2084
Large Business     434
Free Lancer          2
Name: Occupation, dtype: int64

In [17]:
occupation_purchasing_behavior = df[df['ProductPitched'] == 'Deluxe']['Occupation'].value_counts()

In [14]:
occupation_purchasing_behavior

Salaried          818
Small Business    790
Large Business    124
Name: Occupation, dtype: int64

In [51]:
gender_product_preferences = df.groupby(['Gender', 'ProductPitched']).size().unstack(fill_value=0)
gender_product_preferences

ProductPitched  Basic  Deluxe  King  Standard  Super Deluxe
Gender
Fe Male             4      83     0        63             5
Female            676     641    82       263           155
Male             1162    1008   148       416           182

In [24]:
trip_purchase_relationship = df.groupby('NumberOfTrips')['ProductPitched'].value_counts(normalize=True).unstack()

In [25]:
trip_purchase_relationship

ProductPitched     Basic    Deluxe      King  Standard  Super Deluxe
NumberOfTrips
1.0             0.341935  0.382258  0.045161  0.161290      0.069355
2.0             0.444672  0.350410  0.023907  0.140027      0.040984
3.0             0.455978  0.341057  0.018536  0.142725      0.041705
4.0             0.255230  0.384937  0.043933  0.198745      0.117155
5.0             0.296943  0.390830  0.045852  0.181223      0.085153
6.0             0.322981  0.403727  0.043478  0.167702      0.062112
7.0             0.353211  0.362385  0.036697  0.151376      0.096330
8.0             0.390476  0.361905  0.009524  0.161905      0.076190
19.0            1.000000       NaN       NaN       NaN           NaN
20.0            1.000000       NaN       NaN       NaN           NaN
21.0                 NaN  1.000000       NaN       NaN           NaN
22.0                 NaN  1.000000       NaN       NaN           NaN

In [26]:
passport_trip_correlation = df['Passport'].corr(df['NumberOfTrips'])

In [27]:
passport_trip_correlation

0.012948643307955305

In [53]:
customers_with_children = df[df['NumberOfTrips'] > 0]
grouped_by_children = customers_with_children.groupby('NumberOfTrips')
average_purchases_by_children = grouped_by_children['ProductPitched'].value_counts().unstack().fillna(0).mean(axis=1)

In [52]:
df

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [30]:
average_purchases_by_children

NumberOfTrips
1.0     124.0
2.0     292.8
3.0     215.8
4.0      95.6
5.0      91.6
6.0      64.4
7.0      43.6
8.0      21.0
19.0      0.2
20.0      0.2
21.0      0.2
22.0      0.2
dtype: float64

In [31]:
gender_preference=df.groupby('Gender')['PitchSatisfactionScore'].value_counts().unstack(fill_value=0)

In [32]:
gender_preference

PitchSatisfactionScore    1    2    3    4    5
Gender
Fe Male                  36   27   29   32   31
Female                  352  217  537  348  363
Male                    554  342  912  532  576

In [33]:
purchase_by_martial_status=df.groupby('MaritalStatus')['ProductPitched'].value_counts().unstack().fillna(0)
purchase_by_martial_status

ProductPitched  Basic  Deluxe   King  Standard  Super Deluxe
MaritalStatus
Divorced        332.0   336.0   52.0     142.0          88.0
Married         816.0   852.0  126.0     380.0         166.0
Single          511.0   221.0   52.0      50.0          82.0
Unmarried       183.0   323.0    0.0     170.0           6.0

In [34]:
purchase_percentage_by_marital_status = purchase_by_martial_status.div(purchase_by_martial_status.sum(axis=1), axis=0) * 100
purchase_percentage_by_marital_status

ProductPitched      Basic     Deluxe      King   Standard  Super Deluxe
MaritalStatus
Divorced        34.947368  35.368421  5.473684  14.947368      9.263158
Married         34.871795  36.410256  5.384615  16.239316      7.094017
Single          55.786026  24.126638  5.676856   5.458515      8.951965
Unmarried       26.832845  47.360704  0.000000  24.926686      0.879765

In [35]:
no_of_children_by_product_interest=df.groupby('NumberOfChildrenVisiting')['Designation'].value_counts().unstack().fillna(0)
no_of_children_by_product_interest

Designation               AVP  Executive  Manager  Senior Manager  VP
NumberOfChildrenVisiting
0.0                        84        404      391             172  31
1.0                       126        793      754             318  89
2.0                        74        517      474             198  72
3.0                        16        127      112              53  17

In [54]:
no_of_own_car_by_Pitch_duration=df.groupby('OwnCar')['NumberOfTrips'].value_counts().unstack().fillna(0)
no_of_own_car_by_Pitch_duration

NumberOfTrips,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,19.0,20.0,21.0,22.0
OwnCar,,,,,,,,,,,,
0,232,534,408,208,186,120,83,41,0,0,0,0
1,388,930,671,270,272,202,135,64,1,1,1,1

In [39]:
Owncar_trip_correlation = df['OwnCar'].corr(df['NumberOfTrips'])

In [40]:
Owncar_trip_correlation

-0.011824686371922799

In [42]:
IncomeLevel_car_by_ProductPitched=df.groupby('MonthlyIncome')['ProductPitched'].value_counts().unstack().fillna(0)
IncomeLevel_car_by_ProductPitched

ProductPitched  Basic  Deluxe  King  Standard  Super Deluxe
MonthlyIncome
1000.0            0.0     1.0   0.0       0.0           0.0
4678.0            0.0     1.0   0.0       0.0           0.0
16009.0           2.0     0.0   0.0       0.0           0.0
16051.0           2.0     0.0   0.0       0.0           0.0
16052.0           2.0     0.0   0.0       0.0           0.0
...               ...     ...   ...       ...           ...
38621.0           0.0     0.0   2.0       0.0           0.0
38651.0           0.0     0.0   2.0       0.0           0.0
38677.0           0.0     0.0   2.0       0.0           0.0
95000.0           1.0     0.0   0.0       0.0           0.0
98678.0           1.0     0.0   0.0       0.0           0.0

[2475 rows x 5 columns]

In [ ]:
df

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0